/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Product;
import Business.ProductCatalog;
import java.awt.CardLayout;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Malick
 */
public class CreateJPanel extends javax.swing.JPanel {

    Pattern regexTextCheck;
    Pattern regexNumberCheck;

    private JPanel MainJPanel2;
    private ProductCatalog productCatalog;
    private Product p;

    CreateJPanel(JPanel MainJPanel2, ProductCatalog productCatalog) {

        regexTextCheck = Pattern.compile("[a-zA-Z]+");
        regexNumberCheck = Pattern.compile("[0-9]+");
        initComponents();

        this.MainJPanel2 = MainJPanel2;
        this.productCatalog = productCatalog;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreateJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2CProdName = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtProdNam = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtModNo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtVenNam = new javax.swing.JTextField();
        jPanel3CProDes = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtProDes = new javax.swing.JTextArea();
        jPanel4CPrice = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtBasPri = new javax.swing.JTextField();
        txtCeilPri = new javax.swing.JTextField();
        txtFloPri = new javax.swing.JTextField();
        jPanel5CFeature = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtFeature = new javax.swing.JTextArea();
        jPanel6CBenifit = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtBenifits = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();

        CreateJPanel.setBackground(new java.awt.Color(102, 255, 204));
        CreateJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Create the Product Details");
        CreateJPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 11, -1, -1));

        jPanel2CProdName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2CProdName.setName(""); // NOI18N
        jPanel2CProdName.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Product Name");
        jPanel2CProdName.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 17, -1, -1));
        jPanel2CProdName.add(txtProdNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 14, 100, -1));

        jLabel3.setText("Model Number");
        jPanel2CProdName.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 43, -1, -1));

        txtModNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModNoActionPerformed(evt);
            }
        });
        jPanel2CProdName.add(txtModNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 40, 100, -1));

        jLabel4.setText("Vendor Name");
        jPanel2CProdName.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 69, -1, -1));

        txtVenNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVenNamActionPerformed(evt);
            }
        });
        jPanel2CProdName.add(txtVenNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 66, 100, -1));

        CreateJPanel.add(jPanel2CProdName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 51, 419, 100));

        jPanel3CProDes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3CProDes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Product Description");
        jPanel3CProDes.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 35, -1, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        txtProDes.setColumns(20);
        txtProDes.setRows(5);
        jScrollPane1.setViewportView(txtProDes);

        jPanel3CProDes.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 14, 206, 55));

        CreateJPanel.add(jPanel3CProDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 162, 419, 80));

        jPanel4CPrice.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4CPrice.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Base Price");
        jPanel4CPrice.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 17, -1, -1));

        jLabel7.setText("Ceiling Price");
        jPanel4CPrice.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 48, -1, -1));

        jLabel8.setText("Floor Price");
        jPanel4CPrice.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 79, -1, -1));

        txtBasPri.setText(" ");
        txtBasPri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBasPriActionPerformed(evt);
            }
        });
        jPanel4CPrice.add(txtBasPri, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 14, 90, -1));

        txtCeilPri.setText(" ");
        jPanel4CPrice.add(txtCeilPri, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 45, 90, -1));

        txtFloPri.setText(" ");
        jPanel4CPrice.add(txtFloPri, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 76, 90, -1));

        CreateJPanel.add(jPanel4CPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 256, 410, 110));

        jPanel5CFeature.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5CFeature.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Features ");
        jPanel5CFeature.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 14, -1, -1));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        txtFeature.setColumns(20);
        txtFeature.setRows(5);
        jScrollPane2.setViewportView(txtFeature);

        jPanel5CFeature.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 34, 131, -1));

        CreateJPanel.add(jPanel5CFeature, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 51, 160, 150));

        jPanel6CBenifit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6CBenifit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Benefits");
        jPanel6CBenifit.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 14, -1, -1));

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        txtBenifits.setColumns(20);
        txtBenifits.setRows(5);
        jScrollPane3.setViewportView(txtBenifits);

        jPanel6CBenifit.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 131, 110));

        CreateJPanel.add(jPanel6CBenifit, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 219, 157, 150));

        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        CreateJPanel.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 30));

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        CreateJPanel.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CreateJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CreateJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtModNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModNoActionPerformed

    private void txtVenNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVenNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVenNamActionPerformed

    private void txtBasPriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBasPriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBasPriActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        MainJPanel2.remove(this);
        CardLayout layout = (CardLayout) MainJPanel2.getLayout();
        layout.previous(MainJPanel2);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

        if (txtProdNam.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Product Name");
            return;
        }

        if (!regexTextCheck.matcher(txtProdNam.getText()).matches()) {
            JOptionPane.showMessageDialog(null, "Invalid format for First Name");
            return;
        }

        if (txtModNo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter your Model Number");
            return;
        }

        if (!regexNumberCheck.matcher(txtModNo.getText()).matches()) {
            JOptionPane.showMessageDialog(null, "Invalid format for Model Number");
            return;
        }

        if (txtVenNam.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter your Vendor Name");
            return;
        }

        if (!regexTextCheck.matcher(txtVenNam.getText()).matches()) {
            JOptionPane.showMessageDialog(null, "Invalid format for Vendor Name");
            return;
        }
        p = productCatalog.addProduct();
        p.setModelNumber(txtModNo.getText());
        p.setVendorName(txtVenNam.getText());
        p.setModelNumber(txtModNo.getText());
        p.setVendorName(txtVenNam.getText());
        p.setProductName(txtProdNam.getText());
        p.setProductName(txtProdNam.getText());
        p.setProductDescribtion(txtProDes.getText());
        p.setBasePrice(txtBasPri.getText());
        p.setCeilingPrice(txtCeilPri.getText());
        p.setFloorsPrice(txtFloPri.getText());
        p.setFeature(txtFeature.getText());
        p.setBenifits(txtBenifits.getText());

        JOptionPane.showMessageDialog(null, "Your Data is Submitted");

// TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CreateJPanel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2CProdName;
    private javax.swing.JPanel jPanel3CProDes;
    private javax.swing.JPanel jPanel4CPrice;
    private javax.swing.JPanel jPanel5CFeature;
    private javax.swing.JPanel jPanel6CBenifit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtBasPri;
    private javax.swing.JTextArea txtBenifits;
    private javax.swing.JTextField txtCeilPri;
    private javax.swing.JTextArea txtFeature;
    private javax.swing.JTextField txtFloPri;
    private javax.swing.JTextField txtModNo;
    private javax.swing.JTextArea txtProDes;
    private javax.swing.JTextField txtProdNam;
    private javax.swing.JTextField txtVenNam;
    // End of variables declaration//GEN-END:variables
}
