/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Product;
import Business.ProductCatalog;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

  
    public class VendorJPanel extends javax.swing.JPanel {
    
        
        
        private Product P;
        private JPanel MainJPanel2;
    private ProductCatalog productCatalog;
    VendorJPanel(JPanel MainJPanel2, ProductCatalog productCatalog) {
       initComponents();
       
       this.MainJPanel2 = MainJPanel2;
            this.productCatalog = productCatalog;
            
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        SourceJPanel = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        labVen = new javax.swing.JLabel();
        btnSub = new javax.swing.JButton();
        rabtnVendor = new javax.swing.JRadioButton();
        rabtnCustomer = new javax.swing.JRadioButton();
        txtLoginType = new javax.swing.JTextField();

        setBackground(new java.awt.Color(102, 102, 255));

        SourceJPanel.setBackground(new java.awt.Color(153, 153, 255));
        SourceJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        SourceJPanel.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 29, 100, 40));

        labVen.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labVen.setText("Role Selection");
        SourceJPanel.add(labVen, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 70, -1, -1));

        btnSub.setText("Submit");
        btnSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubActionPerformed(evt);
            }
        });
        SourceJPanel.add(btnSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 110, 60));

        rabtnVendor.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroup1.add(rabtnVendor);
        rabtnVendor.setText("Vendor");
        rabtnVendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rabtnVendorActionPerformed(evt);
            }
        });
        SourceJPanel.add(rabtnVendor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 80, 50));

        rabtnCustomer.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroup1.add(rabtnCustomer);
        rabtnCustomer.setText("Customer");
        rabtnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rabtnCustomerActionPerformed(evt);
            }
        });
        SourceJPanel.add(rabtnCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 100, 50));

        txtLoginType.setEnabled(false);
        SourceJPanel.add(txtLoginType, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 86, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SourceJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SourceJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubActionPerformed
        String type = "";
        if(rabtnCustomer.isSelected()){
            type = "Customer";
        }
        else {
            type = "Vendor";
        }
        

        TableJPanel panel = new TableJPanel(MainJPanel2, productCatalog, type);
        MainJPanel2.add("TableJPanel", panel);
        CardLayout layout = (CardLayout) MainJPanel2.getLayout();
        layout.next(MainJPanel2);
          
      

        // TODO add your handling code here:  & (P.getLoginType().equals("Vendor"))
    }//GEN-LAST:event_btnSubActionPerformed

    private void rabtnVendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rabtnVendorActionPerformed

        txtLoginType.setText("Vendor");
    }//GEN-LAST:event_rabtnVendorActionPerformed

    private void rabtnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rabtnCustomerActionPerformed
        txtLoginType.setText("Customer");
    }//GEN-LAST:event_rabtnCustomerActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
         MainJPanel2.remove(this);
        CardLayout layout = (CardLayout) MainJPanel2.getLayout();
        layout.previous(MainJPanel2);




// TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SourceJPanel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSub;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel labVen;
    private javax.swing.JRadioButton rabtnCustomer;
    private javax.swing.JRadioButton rabtnVendor;
    private javax.swing.JTextField txtLoginType;
    // End of variables declaration//GEN-END:variables

   
}
