/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Product;
import Business.ProductCatalog;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Malick
 */
public class ViewJPanel extends javax.swing.JPanel {

    private JPanel MainJPanel2;
    private ProductCatalog productCatalog;
    private Product product;

    ViewJPanel(JPanel MainJPanel2, Product product, String type) {
        initComponents();

        this.MainJPanel2 = MainJPanel2;
        //      this.product = product;
        this.product = product;
        //product = productCatalog.addProduct();
        populateProductDetails();

        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
        txtProdNam.setEditable(false);
        txtModNo.setEditable(false);
        txtVenNam.setEditable(false);
        txtProDes.setEditable(false);
        txtCeilPri.setEditable(false);
        txtBasPri.setEditable(false);
        txtFloPri.setEditable(false);
        txtFeature.setEditable(false);
        txtBenifits.setEditable(false);
        if (type.equals("Customer")) {
            btnSave.setEnabled(false);
            btnUpdate.setEnabled(false);
        }
    }

    private void populateProductDetails() {
        txtProdNam.setText(product.getProductName());
        txtModNo.setText(product.getModelNumber());
        txtVenNam.setText(product.getVendorName());
        txtProDes.setText(product.getProductDescribtion());
        txtCeilPri.setText(product.getCeilingPrice());
        txtBasPri.setText(product.getBasePrice());
        txtFloPri.setText(product.getFeature());
        txtFeature.setText(product.getFeature());
        txtBenifits.setText(product.getBenifits());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ViewJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2VProdName = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtProdNam = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtModNo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtVenNam = new javax.swing.JTextField();
        jPanel3VProDes = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtProDes = new javax.swing.JTextArea();
        jPanel4VPrice = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtBasPri = new javax.swing.JTextField();
        txtCeilPri = new javax.swing.JTextField();
        txtFloPri = new javax.swing.JTextField();
        jPanel5VFeature = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtFeature = new javax.swing.JTextArea();
        jPanel6VBenifit = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtBenifits = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        ViewJPanel.setBackground(new java.awt.Color(204, 204, 255));
        ViewJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("View the Product Details");
        ViewJPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 11, -1, -1));

        jPanel2VProdName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2VProdName.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Praduct Name");
        jPanel2VProdName.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 17, -1, -1));
        jPanel2VProdName.add(txtProdNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 14, 100, -1));

        jLabel3.setText("Model Number");
        jPanel2VProdName.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 43, -1, -1));

        txtModNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModNoActionPerformed(evt);
            }
        });
        jPanel2VProdName.add(txtModNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 40, 100, -1));

        jLabel4.setText("Vender Name");
        jPanel2VProdName.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 69, -1, -1));

        txtVenNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVenNamActionPerformed(evt);
            }
        });
        jPanel2VProdName.add(txtVenNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 66, 100, -1));

        ViewJPanel.add(jPanel2VProdName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 51, 420, 100));

        jPanel3VProDes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3VProDes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Product Description");
        jPanel3VProDes.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 35, -1, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        txtProDes.setColumns(20);
        txtProDes.setRows(5);
        jScrollPane1.setViewportView(txtProDes);

        jPanel3VProDes.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 14, 206, 55));

        ViewJPanel.add(jPanel3VProDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 162, 419, 80));

        jPanel4VPrice.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4VPrice.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Base Price");
        jPanel4VPrice.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 17, -1, -1));

        jLabel7.setText("Ceiling Price");
        jPanel4VPrice.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 48, -1, -1));

        jLabel8.setText("Floors Price");
        jPanel4VPrice.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 79, -1, -1));

        txtBasPri.setText(" ");
        txtBasPri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBasPriActionPerformed(evt);
            }
        });
        jPanel4VPrice.add(txtBasPri, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 14, 90, -1));

        txtCeilPri.setText(" ");
        jPanel4VPrice.add(txtCeilPri, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 45, 90, -1));

        txtFloPri.setText(" ");
        jPanel4VPrice.add(txtFloPri, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 76, 90, -1));

        ViewJPanel.add(jPanel4VPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 256, 420, 110));

        jPanel5VFeature.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5VFeature.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Fetures");
        jPanel5VFeature.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 14, -1, -1));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        txtFeature.setColumns(20);
        txtFeature.setRows(5);
        jScrollPane2.setViewportView(txtFeature);

        jPanel5VFeature.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 34, 125, -1));

        ViewJPanel.add(jPanel5VFeature, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 51, 150, 150));

        jPanel6VBenifit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6VBenifit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Benifits");
        jPanel6VBenifit.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 14, -1, -1));

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        txtBenifits.setColumns(20);
        txtBenifits.setRows(5);
        jScrollPane3.setViewportView(txtBenifits);

        jPanel6VBenifit.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 34, 125, -1));

        ViewJPanel.add(jPanel6VBenifit, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 219, 151, 150));

        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        ViewJPanel.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 100, 30));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        ViewJPanel.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 100, 40));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        ViewJPanel.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 90, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ViewJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ViewJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtModNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModNoActionPerformed

    private void txtVenNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVenNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVenNamActionPerformed

    private void txtBasPriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBasPriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBasPriActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        MainJPanel2.remove(this);
        CardLayout layout = (CardLayout) MainJPanel2.getLayout();
        layout.previous(MainJPanel2);


    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        product.setProductName(txtProdNam.getText());
        product.setModelNumber(txtModNo.getText());
        product.setVendorName(txtVenNam.getText());
        product.setProductDescribtion(txtProDes.getText());
        product.setCeilingPrice(txtCeilPri.getText());
        product.setBasePrice(txtBasPri.getText());
        product.setFloorsPrice(txtFloPri.getText());
        product.setFeature(txtFeature.getText());
        product.setBenifits(txtBenifits.getText());
        txtProdNam.setEditable(false);
        txtModNo.setEditable(false);
        txtVenNam.setEditable(false);
        txtProDes.setEditable(false);
        txtCeilPri.setEditable(false);
        txtBasPri.setEditable(false);
        txtFloPri.setEditable(false);
        txtFeature.setEditable(false);
        txtBenifits.setEditable(false);

        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);

        JOptionPane.showMessageDialog(null, "Details updated successfully"); // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        txtProdNam.setEditable(true);
        txtModNo.setEditable(true);
        txtVenNam.setEditable(true);
        txtProDes.setEditable(true);
        txtCeilPri.setEditable(true);
        txtBasPri.setEditable(true);
        txtFloPri.setEditable(true);
        txtFeature.setEditable(true);
        txtBenifits.setEditable(true);
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ViewJPanel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2VProdName;
    private javax.swing.JPanel jPanel3VProDes;
    private javax.swing.JPanel jPanel4VPrice;
    private javax.swing.JPanel jPanel5VFeature;
    private javax.swing.JPanel jPanel6VBenifit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtBasPri;
    private javax.swing.JTextArea txtBenifits;
    private javax.swing.JTextField txtCeilPri;
    private javax.swing.JTextArea txtFeature;
    private javax.swing.JTextField txtFloPri;
    private javax.swing.JTextField txtModNo;
    private javax.swing.JTextArea txtProDes;
    private javax.swing.JTextField txtProdNam;
    private javax.swing.JTextField txtVenNam;
    // End of variables declaration//GEN-END:variables
}
