/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Transport.Data;

/**
 *
 * @author Malick
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private Data data;
    public MainJFrame() {
        initComponents();
        data=new Data();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPanel = new javax.swing.JSplitPane();
        ControlJPanel = new javax.swing.JPanel();
        GenerateBtn = new javax.swing.JButton();
        ViewBtn = new javax.swing.JButton();
        ClickGenLab = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DisplayJPanel = new javax.swing.JPanel();
        TicGenSysLab = new javax.swing.JLabel();
        BosTraLab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ControlJPanel.setBackground(new java.awt.Color(51, 51, 0));

        GenerateBtn.setText("Generate");
        GenerateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateBtnActionPerformed(evt);
            }
        });

        ViewBtn.setText("View");
        ViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBtnActionPerformed(evt);
            }
        });

        ClickGenLab.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ClickGenLab.setForeground(new java.awt.Color(255, 153, 204));
        ClickGenLab.setText("Click here to generate the ticket");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 204));
        jLabel3.setText("Click here to view the ticket");

        javax.swing.GroupLayout ControlJPanelLayout = new javax.swing.GroupLayout(ControlJPanel);
        ControlJPanel.setLayout(ControlJPanelLayout);
        ControlJPanelLayout.setHorizontalGroup(
            ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlJPanelLayout.createSequentialGroup()
                .addGroup(ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ControlJPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel3))
                    .addGroup(ControlJPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(ClickGenLab))
                    .addGroup(ControlJPanelLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(GenerateBtn))
                    .addGroup(ControlJPanelLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(ViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ControlJPanelLayout.setVerticalGroup(
            ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlJPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(ClickGenLab)
                .addGap(18, 18, 18)
                .addComponent(GenerateBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(ViewBtn)
                .addGap(60, 60, 60))
        );

        SplitPanel.setLeftComponent(ControlJPanel);

        DisplayJPanel.setBackground(new java.awt.Color(153, 255, 255));

        TicGenSysLab.setFont(new java.awt.Font("Vani", 1, 24)); // NOI18N
        TicGenSysLab.setForeground(new java.awt.Color(0, 0, 204));
        TicGenSysLab.setText("Ticket Generating System");

        BosTraLab.setFont(new java.awt.Font("Vani", 1, 24)); // NOI18N
        BosTraLab.setForeground(new java.awt.Color(0, 0, 204));
        BosTraLab.setText("Boston Transport");

        javax.swing.GroupLayout DisplayJPanelLayout = new javax.swing.GroupLayout(DisplayJPanel);
        DisplayJPanel.setLayout(DisplayJPanelLayout);
        DisplayJPanelLayout.setHorizontalGroup(
            DisplayJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayJPanelLayout.createSequentialGroup()
                .addGroup(DisplayJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DisplayJPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(BosTraLab))
                    .addGroup(DisplayJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TicGenSysLab)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        DisplayJPanelLayout.setVerticalGroup(
            DisplayJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayJPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(BosTraLab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TicGenSysLab)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        SplitPanel.setRightComponent(DisplayJPanel);

        getContentPane().add(SplitPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GenerateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateBtnActionPerformed
        CreateJPanel createJPanel = new CreateJPanel(data);
        SplitPanel.setRightComponent(createJPanel);
        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_GenerateBtnActionPerformed

    private void ViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBtnActionPerformed
        ViewJPanel viewJPanel = new ViewJPanel(data);
        SplitPanel.setRightComponent(viewJPanel);
        

// TODO add your handling code here:
    }//GEN-LAST:event_ViewBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BosTraLab;
    private javax.swing.JLabel ClickGenLab;
    private javax.swing.JPanel ControlJPanel;
    private javax.swing.JPanel DisplayJPanel;
    private javax.swing.JButton GenerateBtn;
    private javax.swing.JSplitPane SplitPanel;
    private javax.swing.JLabel TicGenSysLab;
    private javax.swing.JButton ViewBtn;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
