/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Transport.Data;

/**
 *
 * @author Malick
 */

public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    public ViewJPanel(Data data) {
        initComponents();
        DisplayData (data);
        
    }

    private void DisplayData (Data data){
        
        String dataFirstName= data.getFirstName();
        FirNamTex.setText(dataFirstName);
        
        String dataLastName = data.getLastName();
        LasNamTex.setText(dataLastName);
        
        String dataDOB = data.getDOB();
        DOBTex.setText(dataDOB);
        
        String dataSex = data.getSex();
        SexTex.setText(dataSex);
        
        String dataFromStation = data.getFromStation();
        FroStaTex.setText(dataFromStation);
        
        String dataToStation = data.getToStation();
        ToStaTex.setText(dataToStation);


        
    }
            
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TicGenLab = new javax.swing.JLabel();
        FirNamLab = new javax.swing.JLabel();
        FirNamTex = new javax.swing.JTextField();
        LasNamLab = new javax.swing.JLabel();
        LasNamTex = new javax.swing.JTextField();
        DOBLab = new javax.swing.JLabel();
        DOBTex = new javax.swing.JTextField();
        SexLab = new javax.swing.JLabel();
        SexTex = new javax.swing.JTextField();
        FroStaLab = new javax.swing.JLabel();
        FroStaTex = new javax.swing.JTextField();
        ToStaLab = new javax.swing.JLabel();
        ToStaTex = new javax.swing.JTextField();
        PrintBtn = new javax.swing.JButton();
        TicGenLab1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 0));

        TicGenLab.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        TicGenLab.setForeground(new java.awt.Color(255, 0, 0));
        TicGenLab.setText("Ticket Generated");

        FirNamLab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FirNamLab.setForeground(new java.awt.Color(102, 0, 102));
        FirNamLab.setText("First Name");

        FirNamTex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirNamTexActionPerformed(evt);
            }
        });

        LasNamLab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LasNamLab.setForeground(new java.awt.Color(102, 0, 102));
        LasNamLab.setText("Last Name");

        DOBLab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DOBLab.setForeground(new java.awt.Color(102, 0, 102));
        DOBLab.setText("DOB");

        SexLab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SexLab.setForeground(new java.awt.Color(102, 0, 102));
        SexLab.setText("Sex");

        FroStaLab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FroStaLab.setForeground(new java.awt.Color(102, 0, 102));
        FroStaLab.setText("From Station");

        ToStaLab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ToStaLab.setForeground(new java.awt.Color(102, 0, 102));
        ToStaLab.setText("To Station");

        PrintBtn.setBackground(new java.awt.Color(0, 255, 255));
        PrintBtn.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        PrintBtn.setForeground(new java.awt.Color(0, 102, 102));
        PrintBtn.setText("Print Ticket");

        TicGenLab1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        TicGenLab1.setText("Transport Department");

        jLabel1.setText("Ticket Charge: 5$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PrintBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LasNamLab)
                                    .addComponent(FroStaLab)
                                    .addComponent(FirNamLab)
                                    .addComponent(DOBLab)
                                    .addComponent(SexLab)
                                    .addComponent(ToStaLab))
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SexTex)
                                    .addComponent(LasNamTex)
                                    .addComponent(FirNamTex)
                                    .addComponent(DOBTex)
                                    .addComponent(ToStaTex)
                                    .addComponent(FroStaTex, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(TicGenLab1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(TicGenLab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TicGenLab1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TicGenLab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FirNamLab)
                            .addComponent(FirNamTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LasNamLab)
                            .addComponent(LasNamTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DOBLab)
                            .addComponent(DOBTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SexLab)
                            .addComponent(SexTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(FroStaLab)
                                    .addComponent(FroStaTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(ToStaLab))
                            .addComponent(ToStaTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(PrintBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FirNamTexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirNamTexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirNamTexActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DOBLab;
    private javax.swing.JTextField DOBTex;
    private javax.swing.JLabel FirNamLab;
    private javax.swing.JTextField FirNamTex;
    private javax.swing.JLabel FroStaLab;
    private javax.swing.JTextField FroStaTex;
    private javax.swing.JLabel LasNamLab;
    private javax.swing.JTextField LasNamTex;
    private javax.swing.JButton PrintBtn;
    private javax.swing.JLabel SexLab;
    private javax.swing.JTextField SexTex;
    private javax.swing.JLabel TicGenLab;
    private javax.swing.JLabel TicGenLab1;
    private javax.swing.JLabel ToStaLab;
    private javax.swing.JTextField ToStaTex;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
