/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Student.Resume;
import Student.ResumeHistory;
import java.io.File;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author Malick
 */
  public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */

    private String Pic;
    private Resume r;
    Pattern regexTextCheck;
    Pattern regexNumberCheck;
   
    
    private ResumeHistory rmh;
    public CreateJPanel(ResumeHistory rmh) {
        regexTextCheck = Pattern.compile("[a-zA-Z]+");
        regexNumberCheck = Pattern.compile("[0-9]+");
        initComponents();
        this.rmh=rmh;
        r = rmh.addResume();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RadBtnGrp = new javax.swing.ButtonGroup();
        RadBtnGrpCiti = new javax.swing.ButtonGroup();
        RadBtnGrpDeg = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        SubPanScr = new javax.swing.JPanel();
        HeadlingLab = new javax.swing.JLabel();
        FirNamLab = new javax.swing.JLabel();
        LasNamLab = new javax.swing.JLabel();
        PicLab = new javax.swing.JLabel();
        NUIDLab = new javax.swing.JLabel();
        AddLab = new javax.swing.JLabel();
        Str1Lab = new javax.swing.JLabel();
        Str2Lab = new javax.swing.JLabel();
        CityLab = new javax.swing.JLabel();
        CountryLab = new javax.swing.JLabel();
        AffLab = new javax.swing.JLabel();
        CarObjLab = new javax.swing.JLabel();
        EduLab = new javax.swing.JLabel();
        DegLab = new javax.swing.JLabel();
        MajLab = new javax.swing.JLabel();
        DateLab = new javax.swing.JLabel();
        WorExpLab = new javax.swing.JLabel();
        ComNamLab = new javax.swing.JLabel();
        TitLab = new javax.swing.JLabel();
        DurLab = new javax.swing.JLabel();
        SexLab = new javax.swing.JLabel();
        FirNamTxe = new javax.swing.JTextField();
        LasNamTxe = new javax.swing.JTextField();
        NUIDTex = new javax.swing.JTextField();
        StrLin1Txe = new javax.swing.JTextField();
        StrLin2Tex = new javax.swing.JTextField();
        CityTxe = new javax.swing.JTextField();
        CouTex = new javax.swing.JTextField();
        AffTex = new javax.swing.JTextField();
        EMjTex = new javax.swing.JTextField();
        EDaTex = new javax.swing.JTextField();
        WTiTex = new javax.swing.JTextField();
        WCoTex = new javax.swing.JTextField();
        WDurTex = new javax.swing.JTextField();
        PicTex = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        CarObjTex = new javax.swing.JTextArea();
        MalRadBtn = new javax.swing.JRadioButton();
        FemRadBtn = new javax.swing.JRadioButton();
        UpPicBtn = new javax.swing.JButton();
        CerLab = new javax.swing.JLabel();
        SkiLab = new javax.swing.JLabel();
        CerTex = new javax.swing.JTextField();
        SubmitBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ClearBtn = new javax.swing.JButton();
        JavChk = new javax.swing.JCheckBox();
        RubChk = new javax.swing.JCheckBox();
        PhyChk = new javax.swing.JCheckBox();
        CobChk = new javax.swing.JCheckBox();
        LabCitizen = new javax.swing.JLabel();
        RadBtnUsa = new javax.swing.JRadioButton();
        RadBtnInt = new javax.swing.JRadioButton();
        RabBtnBS = new javax.swing.JRadioButton();
        RadBtnMS = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(204, 255, 0));

        SubPanScr.setBackground(new java.awt.Color(204, 255, 51));

        HeadlingLab.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        HeadlingLab.setText("Enter your Details");

        FirNamLab.setText("First Name");

        LasNamLab.setText("Last Name");

        PicLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/default.png-128x128x2.png"))); // NOI18N
        PicLab.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        NUIDLab.setText("NU ID");

        AddLab.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        AddLab.setText("Address");

        Str1Lab.setText("Street Line 1");

        Str2Lab.setText("Street Line 2");

        CityLab.setText("City");

        CountryLab.setText("Country");

        AffLab.setText("Affiliation");

        CarObjLab.setText("Carrier Objective Statement");

        EduLab.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EduLab.setText("Education");

        DegLab.setText("Degree");

        MajLab.setText("Major");

        DateLab.setText("Dated");

        WorExpLab.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        WorExpLab.setText("Work Experience");

        ComNamLab.setText("Company Name");

        TitLab.setText("Title");

        DurLab.setText("Duration");

        SexLab.setText("Sex");

        FirNamTxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirNamTxeActionPerformed(evt);
            }
        });

        LasNamTxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LasNamTxeActionPerformed(evt);
            }
        });

        NUIDTex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUIDTexActionPerformed(evt);
            }
        });

        StrLin1Txe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StrLin1TxeActionPerformed(evt);
            }
        });

        StrLin2Tex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StrLin2TexActionPerformed(evt);
            }
        });

        CityTxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityTxeActionPerformed(evt);
            }
        });

        CouTex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CouTexActionPerformed(evt);
            }
        });

        AffTex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AffTexActionPerformed(evt);
            }
        });

        EMjTex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EMjTexActionPerformed(evt);
            }
        });

        EDaTex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDaTexActionPerformed(evt);
            }
        });

        WTiTex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WTiTexActionPerformed(evt);
            }
        });

        WCoTex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WCoTexActionPerformed(evt);
            }
        });

        WDurTex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WDurTexActionPerformed(evt);
            }
        });

        PicTex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PicTexActionPerformed(evt);
            }
        });

        CarObjTex.setColumns(20);
        CarObjTex.setRows(5);
        jScrollPane1.setViewportView(CarObjTex);

        MalRadBtn.setBackground(new java.awt.Color(204, 255, 51));
        RadBtnGrp.add(MalRadBtn);
        MalRadBtn.setText("Male");
        MalRadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MalRadBtnActionPerformed(evt);
            }
        });

        FemRadBtn.setBackground(new java.awt.Color(204, 255, 51));
        RadBtnGrp.add(FemRadBtn);
        FemRadBtn.setText("Female");
        FemRadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemRadBtnActionPerformed(evt);
            }
        });

        UpPicBtn.setText("Upload Picture");
        UpPicBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpPicBtnActionPerformed(evt);
            }
        });

        CerLab.setText("Certifications");

        SkiLab.setText("Skills");

        CerTex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerTexActionPerformed(evt);
            }
        });

        SubmitBtn.setBackground(new java.awt.Color(0, 0, 0));
        SubmitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/button-submit.png"))); // NOI18N
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });

        ClearBtn.setBackground(new java.awt.Color(0, 0, 0));
        ClearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/clear_button.gif"))); // NOI18N
        ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBtnActionPerformed(evt);
            }
        });

        JavChk.setBackground(new java.awt.Color(204, 255, 51));
        JavChk.setText("Java");

        RubChk.setBackground(new java.awt.Color(204, 255, 51));
        RubChk.setText("Ruby");

        PhyChk.setBackground(new java.awt.Color(204, 255, 51));
        PhyChk.setText("Phython");
        PhyChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhyChkActionPerformed(evt);
            }
        });

        CobChk.setBackground(new java.awt.Color(204, 255, 51));
        CobChk.setText("COBOL");

        LabCitizen.setText("Citizenship");

        RadBtnUsa.setBackground(new java.awt.Color(204, 255, 51));
        RadBtnGrpCiti.add(RadBtnUsa);
        RadBtnUsa.setText("USA");
        RadBtnUsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadBtnUsaActionPerformed(evt);
            }
        });

        RadBtnInt.setBackground(new java.awt.Color(204, 255, 51));
        RadBtnGrpCiti.add(RadBtnInt);
        RadBtnInt.setText("International");
        RadBtnInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadBtnIntActionPerformed(evt);
            }
        });

        RabBtnBS.setBackground(new java.awt.Color(204, 255, 51));
        RadBtnGrpDeg.add(RabBtnBS);
        RabBtnBS.setText("B.S");
        RabBtnBS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RabBtnBSActionPerformed(evt);
            }
        });

        RadBtnMS.setBackground(new java.awt.Color(204, 255, 51));
        RadBtnGrpDeg.add(RadBtnMS);
        RadBtnMS.setText("M.S");
        RadBtnMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadBtnMSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SubPanScrLayout = new javax.swing.GroupLayout(SubPanScr);
        SubPanScr.setLayout(SubPanScrLayout);
        SubPanScrLayout.setHorizontalGroup(
            SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubPanScrLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SubPanScrLayout.createSequentialGroup()
                        .addComponent(CarObjLab)
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SubPanScrLayout.createSequentialGroup()
                        .addGroup(SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SubPanScrLayout.createSequentialGroup()
                                .addComponent(HeadlingLab)
                                .addGap(66, 66, 66))
                            .addGroup(SubPanScrLayout.createSequentialGroup()
                                .addGroup(SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(SubPanScrLayout.createSequentialGroup()
                                            .addComponent(FirNamLab)
                                            .addGap(18, 18, 18)
                                            .addComponent(FirNamTxe, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(SubPanScrLayout.createSequentialGroup()
                                            .addComponent(NUIDLab)
                                            .addGap(40, 40, 40)
                                            .addComponent(NUIDTex, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(52, 52, 52)))
                                    .addGroup(SubPanScrLayout.createSequentialGroup()
                                        .addComponent(SexLab)
                                        .addGap(50, 50, 50)
                                        .addComponent(MalRadBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(FemRadBtn))
                                    .addGroup(SubPanScrLayout.createSequentialGroup()
                                        .addComponent(LasNamLab)
                                        .addGap(18, 18, 18)
                                        .addComponent(LasNamTxe, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(225, 225, 225)))
                        .addGroup(SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UpPicBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PicTex, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(SubPanScrLayout.createSequentialGroup()
                                .addComponent(PicLab, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))))
                    .addGroup(SubPanScrLayout.createSequentialGroup()
                        .addGroup(SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SubPanScrLayout.createSequentialGroup()
                                .addComponent(AddLab)
                                .addGap(28, 28, 28)
                                .addGroup(SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AffTex, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(SubPanScrLayout.createSequentialGroup()
                                        .addGroup(SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(SubPanScrLayout.createSequentialGroup()
                                                .addComponent(CityLab)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(CityTxe, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(SubPanScrLayout.createSequentialGroup()
                                                .addComponent(Str1Lab)
                                                .addGap(18, 18, 18)
                                                .addComponent(StrLin1Txe, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(47, 47, 47)
                                        .addGroup(SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(SubPanScrLayout.createSequentialGroup()
                                                .addComponent(CountryLab)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(CouTex, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(SubPanScrLayout.createSequentialGroup()
                                                .addGroup(SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(LabCitizen)
                                                    .addComponent(Str2Lab))
                                                .addGap(18, 18, 18)
                                                .addGroup(SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(RadBtnUsa)
                                                    .addComponent(StrLin2Tex, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addComponent(AffLab))
                        .addComponent(RadBtnInt))
                    .addGroup(SubPanScrLayout.createSequentialGroup()
                        .addGroup(SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CerLab)
                            .addComponent(SkiLab))
                        .addGroup(SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SubPanScrLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(CerTex, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SubPanScrLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(JavChk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RubChk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PhyChk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CobChk))))
                    .addGroup(SubPanScrLayout.createSequentialGroup()
                        .addComponent(WorExpLab)
                        .addGap(18, 18, 18)
                        .addGroup(SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComNamLab)
                            .addComponent(DurLab, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(WDurTex, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WCoTex, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SubPanScrLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(ClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SubPanScrLayout.createSequentialGroup()
                                .addComponent(TitLab)
                                .addGap(26, 26, 26)
                                .addComponent(WTiTex, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(SubPanScrLayout.createSequentialGroup()
                        .addComponent(EduLab)
                        .addGap(18, 18, 18)
                        .addComponent(DegLab)
                        .addGap(18, 18, 18)
                        .addGroup(SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RabBtnBS)
                            .addComponent(RadBtnMS))
                        .addGap(18, 18, 18)
                        .addComponent(MajLab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EMjTex, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(DateLab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EDaTex, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(128, 128, 128))
        );
        SubPanScrLayout.setVerticalGroup(
            SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubPanScrLayout.createSequentialGroup()
                .addGroup(SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(SubPanScrLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(SubPanScrLayout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jLabel1)
                                .addGap(0, 39, Short.MAX_VALUE))
                            .addGroup(SubPanScrLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(PicLab, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5))))
                    .addGroup(SubPanScrLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(HeadlingLab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FirNamLab)
                            .addComponent(FirNamTxe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LasNamTxe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LasNamLab))
                        .addGap(5, 5, 5)))
                .addGroup(SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NUIDLab)
                    .addGroup(SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NUIDTex, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PicTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UpPicBtn)
                    .addGroup(SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SexLab)
                        .addComponent(MalRadBtn)
                        .addComponent(FemRadBtn)))
                .addGap(9, 9, 9)
                .addGroup(SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddLab)
                    .addComponent(Str1Lab)
                    .addComponent(Str2Lab)
                    .addComponent(StrLin1Txe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StrLin2Tex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CityLab)
                    .addComponent(CountryLab)
                    .addComponent(CityTxe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CouTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AffLab)
                    .addComponent(AffTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabCitizen)
                    .addComponent(RadBtnUsa)
                    .addComponent(RadBtnInt))
                .addGap(18, 18, 18)
                .addGroup(SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CarObjLab)
                    .addGroup(SubPanScrLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SubPanScrLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RabBtnBS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RadBtnMS)
                        .addGap(1, 1, 1))
                    .addGroup(SubPanScrLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(EduLab)
                                .addComponent(DegLab))
                            .addGroup(SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(MajLab)
                                .addComponent(DateLab)
                                .addComponent(EMjTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(EDaTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CerTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CerLab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SkiLab)
                    .addComponent(JavChk)
                    .addComponent(RubChk)
                    .addComponent(PhyChk)
                    .addComponent(CobChk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WorExpLab)
                    .addComponent(ComNamLab)
                    .addComponent(TitLab)
                    .addComponent(WTiTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WCoTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(WDurTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DurLab))
                    .addGroup(SubPanScrLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(SubPanScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jScrollPane2.setViewportView(SubPanScr);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void WDurTexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WDurTexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WDurTexActionPerformed

    private void WCoTexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WCoTexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WCoTexActionPerformed

    private void WTiTexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WTiTexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WTiTexActionPerformed

    private void EDaTexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDaTexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EDaTexActionPerformed

    private void EMjTexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EMjTexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EMjTexActionPerformed

    private void AffTexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AffTexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AffTexActionPerformed

    private void CouTexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CouTexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CouTexActionPerformed

    private void CityTxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityTxeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CityTxeActionPerformed

    private void StrLin2TexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StrLin2TexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StrLin2TexActionPerformed

    private void StrLin1TxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StrLin1TxeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StrLin1TxeActionPerformed

    private void NUIDTexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUIDTexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NUIDTexActionPerformed

    private void LasNamTxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LasNamTxeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LasNamTxeActionPerformed

    private void FirNamTxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirNamTxeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirNamTxeActionPerformed

    private void PicTexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PicTexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PicTexActionPerformed

    private void UpPicBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpPicBtnActionPerformed
      JFileChooser chooser = new JFileChooser();
      chooser.showOpenDialog(null);
      File f=chooser.getSelectedFile();
      String filename=f.getAbsolutePath(); 
      PicTex.setText(filename);
      Pic=filename;
        // TODO add your handling code here:
    }//GEN-LAST:event_UpPicBtnActionPerformed

    private void CerTexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerTexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CerTexActionPerformed

    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
        // TODO add your handling code here:
      
       r.setLastName(FirNamTxe.getText());
      if(FirNamTxe.getText().equals("")){
          JOptionPane.showMessageDialog(null, "Enter your First name");
          return;
      }
      if(regexTextCheck.matcher(FirNamTxe.getText()).matches()){
         r.setFirstName(FirNamTxe.getText());
      } else {
          JOptionPane.showMessageDialog(null, "Invalid format for First Name");
          return;
      }
      
      
      
      
       r.setLastName(LasNamTxe.getText());
      if(LasNamTxe.getText().equals("")){
          JOptionPane.showMessageDialog(null, "Enter your last name");
          return;
      }
      if(regexTextCheck.matcher(LasNamTxe.getText()).matches()){
         r.setLastName(LasNamTxe.getText());
      } else {
          JOptionPane.showMessageDialog(null, "Invalid format for lastname");
          return;
      }
      
      
      
      
      
      
      String a = NUIDTex.getText();
      System.out.println(a);
      
      
      
      if(NUIDTex.getText().equals("")){
          JOptionPane.showMessageDialog(null, "Enter the your NUID");
          return;
      }
      if(regexNumberCheck.matcher(NUIDTex.getText()).matches()){
          r.setNUID(NUIDTex.getText());
      } else {
          JOptionPane.showMessageDialog(null, "Invalid format for NUID");
          return;
      }
      

//      r.setSex(SexTex.getText());
      r.setStreetLine1(StrLin1Txe.getText());
      r.setStreetLine2(StrLin2Tex.getText());
      r.setCity(CityTxe.getText());
      r.setCountry(CouTex.getText());
      r.setAffiliation(AffTex.getText());
      r.setObjective(CarObjTex.getText());
//      r.setEDegree(EdgTex.getText());
      r.setEMajor(EMjTex.getText());
      r.setEdate(EDaTex.getText());
      r.setWCompanyName(WCoTex.getText());
      r.setWTitle(WTiTex.getText());
      r.setWDuration(WDurTex.getText());
      r.setCertifications(CerTex.getText());
    //  r.setSkills(SkiTex.getText());
      r.setPicture(Pic);
       
       if(JavChk.isSelected())
        {
            r.setSkills("Java");
        }
       else{
           r.setSkills("");
       }
       
       
       
      
        if(RubChk.isSelected())
        {
            r.setSkill1("Ruby");
        } 
        else{
            r.setSkill1("");
        }
           
        
        
        if(PhyChk.isSelected())
        { 
            r.setSkill2("Phython");
        }
        else{
            r.setSkill2("");
        }
      
        
        
        
        if(CobChk.isSelected())
        { 
            r.setSkill3("COBOL");
        }
        else{
            r.setSkill3("");
        }
        
        
        
       
        
      //  resume.setFirstName(FirNamTxe.getText());
      //  resume.setLastName(LasNamTxe.getText());
      //  resume.setNUID(NUIDTex.getText());
      //  resume.setSex(SexTex.getText());
      //  resume.setStreetLine1(StrLin1Txe.getText());
      //  resume.setStreetLine2(StrLin2Tex.getText());
      //  resume.setCity(CityTxe.getText());
      //  resume.setCountry(CouTex.getText());
      //  resume.setAffiliation(AffTex.getText());
      //  resume.setObjective(CarObjTex.getText());
      //  resume.setEDegree(EdgTex.getText());
      //  resume.setEMajor(EMjTex.getText());
      //  resume.setEdate(EDaTex.getText());
      //  resume.setWCompanyName(WCoTex.getText());
      //  resume.setWTitle(WTiTex.getText());
      //  resume.setWDuration(WDurTex.getText());
      //  resume.setCertifications(CerTex.getText());
      //  resume.setSkills(SkiTex.getText());
      //  resume.setPicture(Pic);
       JOptionPane.showMessageDialog(null,"Your Resume is Submitted");
       
//       FirNamTxe.setText("");
//       LasNamTxe.setText("");
//       NUIDTex.setText("");
//     SexTex.setText("");
//       StrLin1Txe.setText("");
//       StrLin2Tex.setText("");     
//       CityTxe.setText("");
//       CouTex.setText("");
//       AffTex.setText("");
//       CarObjTex.setText("");
//       EdgTex.setText("");
//       EMjTex.setText("");
//       EDaTex.setText("");
//       WCoTex.setText("");
//       WTiTex.setText("");
//       WDurTex.setText("");
//       CerTex.setText("");
//       SkiTex.setText("");
  
       
       
    }//GEN-LAST:event_SubmitBtnActionPerformed

    private void MalRadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MalRadBtnActionPerformed
    //    SexTex.setText("Male");
        r.setSex("Male");
    }//GEN-LAST:event_MalRadBtnActionPerformed

    private void FemRadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemRadBtnActionPerformed
    //    SexTex.setText("Female");
     
        r.setSex("Female");    
// TODO add your handling code here:
    }//GEN-LAST:event_FemRadBtnActionPerformed

    private void ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBtnActionPerformed
        FirNamTxe.setText("");  
        LasNamTxe.setText(""); 
        NUIDTex.setText(""); 
    //    SexTex.setText(""); 
        PicTex.setText(""); 
        StrLin1Txe.setText(""); 
        StrLin2Tex.setText(""); 
        CityTxe.setText(""); 
        CouTex.setText(""); 
        AffTex.setText(""); 
        CarObjTex.setText(""); 
        CerTex.setText(""); 
 //       SkiTex.setText(""); 
 //       EdgTex.setText(""); 
        EMjTex.setText(""); 
        EDaTex.setText(""); 
        WCoTex.setText(""); 
        WTiTex.setText(""); 
        WDurTex.setText(""); 
        RadBtnGrp.clearSelection();
        JavChk.setSelected(false);
        RubChk.setSelected(false);
        PhyChk.setSelected(false);
        CobChk.setSelected(false);    
       
        
        
        
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_ClearBtnActionPerformed

    private void PhyChkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhyChkActionPerformed
        
    }//GEN-LAST:event_PhyChkActionPerformed

    private void RadBtnUsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadBtnUsaActionPerformed
      r.setCitizenship("USA");

// TODO add your handling code here:
    }//GEN-LAST:event_RadBtnUsaActionPerformed

    private void RadBtnIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadBtnIntActionPerformed
         r.setCitizenship("International");
            
    // TODO add your handling code here:
    }//GEN-LAST:event_RadBtnIntActionPerformed

    private void RadBtnMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadBtnMSActionPerformed
        r.setEDegree("Masters");

// TODO add your handling code here:
    }//GEN-LAST:event_RadBtnMSActionPerformed

    private void RabBtnBSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RabBtnBSActionPerformed
        r.setEDegree("Bachelors");


// TODO add your handling code here:
    }//GEN-LAST:event_RabBtnBSActionPerformed
       
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddLab;
    private javax.swing.JLabel AffLab;
    private javax.swing.JTextField AffTex;
    private javax.swing.JLabel CarObjLab;
    private javax.swing.JTextArea CarObjTex;
    private javax.swing.JLabel CerLab;
    private javax.swing.JTextField CerTex;
    private javax.swing.JLabel CityLab;
    private javax.swing.JTextField CityTxe;
    private javax.swing.JButton ClearBtn;
    private javax.swing.JCheckBox CobChk;
    private javax.swing.JLabel ComNamLab;
    private javax.swing.JTextField CouTex;
    private javax.swing.JLabel CountryLab;
    private javax.swing.JLabel DateLab;
    private javax.swing.JLabel DegLab;
    private javax.swing.JLabel DurLab;
    private javax.swing.JTextField EDaTex;
    private javax.swing.JTextField EMjTex;
    private javax.swing.JLabel EduLab;
    private javax.swing.JRadioButton FemRadBtn;
    private javax.swing.JLabel FirNamLab;
    private javax.swing.JTextField FirNamTxe;
    private javax.swing.JLabel HeadlingLab;
    private javax.swing.JCheckBox JavChk;
    private javax.swing.JLabel LabCitizen;
    private javax.swing.JLabel LasNamLab;
    private javax.swing.JTextField LasNamTxe;
    private javax.swing.JLabel MajLab;
    private javax.swing.JRadioButton MalRadBtn;
    private javax.swing.JLabel NUIDLab;
    private javax.swing.JTextField NUIDTex;
    private javax.swing.JCheckBox PhyChk;
    private javax.swing.JLabel PicLab;
    private javax.swing.JTextField PicTex;
    private javax.swing.JRadioButton RabBtnBS;
    private javax.swing.ButtonGroup RadBtnGrp;
    private javax.swing.ButtonGroup RadBtnGrpCiti;
    private javax.swing.ButtonGroup RadBtnGrpDeg;
    private javax.swing.JRadioButton RadBtnInt;
    private javax.swing.JRadioButton RadBtnMS;
    private javax.swing.JRadioButton RadBtnUsa;
    private javax.swing.JCheckBox RubChk;
    private javax.swing.JLabel SexLab;
    private javax.swing.JLabel SkiLab;
    private javax.swing.JLabel Str1Lab;
    private javax.swing.JLabel Str2Lab;
    private javax.swing.JTextField StrLin1Txe;
    private javax.swing.JTextField StrLin2Tex;
    private javax.swing.JPanel SubPanScr;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JLabel TitLab;
    private javax.swing.JButton UpPicBtn;
    private javax.swing.JTextField WCoTex;
    private javax.swing.JTextField WDurTex;
    private javax.swing.JTextField WTiTex;
    private javax.swing.JLabel WorExpLab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
