/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Student.Resume;
import Student.ResumeHistory;






/**
 *
 * @author Malick
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private ResumeHistory rmh;
    
    public MainJFrame() {
        initComponents();
        rmh = new ResumeHistory();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPane = new javax.swing.JSplitPane();
        ControlJPanel = new javax.swing.JPanel();
        CreBtn = new javax.swing.JButton();
        VieBtn = new javax.swing.JButton();
        CliCreLab = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ViewJPanel = new javax.swing.JPanel();
        NEULab = new javax.swing.JLabel();
        BlueJPanel = new javax.swing.JPanel();
        OnCamLab = new javax.swing.JLabel();
        StudentsLab = new javax.swing.JLabel();
        NSealPic = new javax.swing.JLabel();
        NPic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ControlJPanel.setBackground(new java.awt.Color(153, 255, 153));

        CreBtn.setText("Create");
        CreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreBtnActionPerformed(evt);
            }
        });

        VieBtn.setText("View");
        VieBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VieBtnActionPerformed(evt);
            }
        });

        CliCreLab.setText("Click here to create your resume");

        jLabel1.setText("Click here to View your Resume");

        javax.swing.GroupLayout ControlJPanelLayout = new javax.swing.GroupLayout(ControlJPanel);
        ControlJPanel.setLayout(ControlJPanelLayout);
        ControlJPanelLayout.setHorizontalGroup(
            ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CliCreLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(ControlJPanelLayout.createSequentialGroup()
                .addGroup(ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ControlJPanelLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(VieBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ControlJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(ControlJPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(CreBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ControlJPanelLayout.setVerticalGroup(
            ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlJPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(CliCreLab)
                .addGap(18, 18, 18)
                .addComponent(CreBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(VieBtn)
                .addGap(97, 97, 97))
        );

        SplitPane.setLeftComponent(ControlJPanel);

        ViewJPanel.setBackground(new java.awt.Color(255, 255, 255));

        NEULab.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        NEULab.setForeground(new java.awt.Color(255, 0, 0));
        NEULab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NEULab.setText("Northeastern University ");
        NEULab.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        BlueJPanel.setBackground(new java.awt.Color(153, 153, 255));

        OnCamLab.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        OnCamLab.setText("On Campus Job Fair");

        StudentsLab.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        StudentsLab.setText("Students who are interested in oncampus job can apply by creating their resume in our portal ");

        NSealPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/WarmGraySeal.png"))); // NOI18N

        javax.swing.GroupLayout BlueJPanelLayout = new javax.swing.GroupLayout(BlueJPanel);
        BlueJPanel.setLayout(BlueJPanelLayout);
        BlueJPanelLayout.setHorizontalGroup(
            BlueJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BlueJPanelLayout.createSequentialGroup()
                .addGroup(BlueJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BlueJPanelLayout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(OnCamLab))
                    .addGroup(BlueJPanelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(StudentsLab))
                    .addGroup(BlueJPanelLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(NSealPic)))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        BlueJPanelLayout.setVerticalGroup(
            BlueJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BlueJPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(OnCamLab)
                .addGap(18, 18, 18)
                .addComponent(StudentsLab)
                .addGap(18, 18, 18)
                .addComponent(NSealPic)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        NPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/northeastern.40.png"))); // NOI18N

        javax.swing.GroupLayout ViewJPanelLayout = new javax.swing.GroupLayout(ViewJPanel);
        ViewJPanel.setLayout(ViewJPanelLayout);
        ViewJPanelLayout.setHorizontalGroup(
            ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BlueJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ViewJPanelLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(NPic)
                .addGap(18, 18, 18)
                .addComponent(NEULab)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ViewJPanelLayout.setVerticalGroup(
            ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewJPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NEULab)
                    .addComponent(NPic))
                .addGap(18, 18, 18)
                .addComponent(BlueJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SplitPane.setRightComponent(ViewJPanel);

        getContentPane().add(SplitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreBtnActionPerformed
       CreateJPanel createJPanel = new CreateJPanel(rmh);
       SplitPane.setRightComponent(createJPanel);
       
       

// TODO add your handling code here:
    }//GEN-LAST:event_CreBtnActionPerformed

    private void VieBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VieBtnActionPerformed
        ViewJPanel viewJPanel = new ViewJPanel(rmh);
       SplitPane.setRightComponent(viewJPanel);
        

// TODO add your handling code here:
    }//GEN-LAST:event_VieBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
         
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BlueJPanel;
    private javax.swing.JLabel CliCreLab;
    private javax.swing.JPanel ControlJPanel;
    private javax.swing.JButton CreBtn;
    private javax.swing.JLabel NEULab;
    private javax.swing.JLabel NPic;
    private javax.swing.JLabel NSealPic;
    private javax.swing.JLabel OnCamLab;
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JLabel StudentsLab;
    private javax.swing.JButton VieBtn;
    private javax.swing.JPanel ViewJPanel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
