/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Student.Resume;
import Student.ResumeHistory;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
 
/**
 *
 * @author Malick
 */

public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    private ResumeHistory rmh;
    public ViewJPanel(ResumeHistory rmh) {
        initComponents();
        this.rmh = rmh;
        populateTable();
        
    }
//
//    public ViewJPanel(Resume resume) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }
    
    public void populateTable()
    {
      DefaultTableModel dtm = (DefaultTableModel)VitalJTable.getModel();
      dtm.setRowCount(0);
      
      for(Resume rm : rmh.getresumeHistory())
      {
          Object row[] = new Object[2];
          row[0] = rm; 
          row[1] = rm.getFirstName();
          dtm.addRow(row);
          
      }
    }
    private void DisplayResume(Resume resume) {
        
           /*     
       
        ImageIcon ProfilePic=new ImageIcon(resume.getPicture());
        PicLab.setIcon(ProfilePic);
        //PicLab.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        //BufferedImage img =null;
        //try { img =ImageIO.read(newFile("strawberry.jpg"));}
        //catch(IOException e) {e.printStackTrace();}
        //BufferedImage ProfilePic = img.getScaledInstance(label.width, label.height,Image.PicLab);

        String FirstName=resume.getFirstName();
        FirNameTex.setText(FirstName);
        
        String LastName=resume.getLastName();
        LasNamTex.setText(LastName);
        
        String NUID=resume.getNUID();
        NUIDTex.setText(NUID);
        
        String Sex=resume.getSex();
        SexTex.setText(Sex);
        
        String Street1=resume.getStreetLine1();
        StrLin1Tex.setText(Street1);
        
        String Street2=resume.getStreetLine2();
        StrLin2Tex.setText(Street2);
        
        String City=resume.getCity();
        CityTex.setText(City);
        
        String Country=resume.getCountry();
        CouTex.setText(Country);
        
        String Affiliation=resume.getAffiliation();
        AffTex.setText(Affiliation);
        
        String Carrier=resume.getObjective();
        CarObjTex.setText(Carrier);
        
        String EDegree=resume.getEDegree();
        EDegTex.setText(EDegree);
        
        String EMajor=resume.getEDegree();
        EDegTex.setText(EMajor);
        
        String Edate=resume.getEdate();
        EDatTex.setText(Edate);
        
        String WCompany=resume.getWCompanyName();
        WCNamTex.setText(WCompany);
        
        String WTitle=resume.getWTitle();
        WTitTex.setText(WTitle);
        
        String WDuration=resume.getWDuration();
        WDurTex.setText(WDuration);
        
        String Certifications=resume.getCertifications();
        CerTex.setText(Certifications);
        
        String Skills=resume.getSkills();
        SkiTex.setText(Skills);
        
        */ 
        
       
   
        
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        ScrJPanel = new javax.swing.JPanel();
        ComNamLab = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CarObjTex = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        CarObjTex1 = new javax.swing.JTextArea();
        TitLab = new javax.swing.JLabel();
        SexLab = new javax.swing.JLabel();
        FirNamLab = new javax.swing.JLabel();
        DurLab = new javax.swing.JLabel();
        FirNameTex = new javax.swing.JTextField();
        LasNamLab = new javax.swing.JLabel();
        LasNamTex = new javax.swing.JTextField();
        NUIDLab = new javax.swing.JLabel();
        NUIDTex = new javax.swing.JTextField();
        StrLin1Tex = new javax.swing.JTextField();
        AddLab = new javax.swing.JLabel();
        StrLin2Tex = new javax.swing.JTextField();
        Str1Lab = new javax.swing.JLabel();
        CityTex = new javax.swing.JTextField();
        Str2Lab = new javax.swing.JLabel();
        CityLab = new javax.swing.JLabel();
        CerLab = new javax.swing.JLabel();
        CouTex = new javax.swing.JTextField();
        SkiLab = new javax.swing.JLabel();
        AffTex = new javax.swing.JTextField();
        CountryLab = new javax.swing.JLabel();
        EDegTex = new javax.swing.JTextField();
        CerTex = new javax.swing.JTextField();
        AffLab = new javax.swing.JLabel();
        EMajTex = new javax.swing.JTextField();
        SkiTex = new javax.swing.JTextField();
        CarObjLab = new javax.swing.JLabel();
        EDatTex = new javax.swing.JTextField();
        EduLab = new javax.swing.JLabel();
        WTitTex = new javax.swing.JTextField();
        DegLab = new javax.swing.JLabel();
        WCNamTex = new javax.swing.JTextField();
        MajLab = new javax.swing.JLabel();
        WDurTex = new javax.swing.JTextField();
        DateLab = new javax.swing.JLabel();
        WorExpLab = new javax.swing.JLabel();
        HeadlingLab = new javax.swing.JLabel();
        SexTex = new javax.swing.JTextField();
        PicLab = new javax.swing.JLabel();
        ExiBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        VitalJTable = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        VitalJTable1 = new javax.swing.JTable();
        VieBtn = new javax.swing.JButton();
        DelBtn = new javax.swing.JButton();
        LabCitizen = new javax.swing.JLabel();
        TexCitizen = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 153, 255));

        ScrJPanel.setBackground(new java.awt.Color(204, 102, 255));

        ComNamLab.setText("Company Name");

        CarObjTex.setColumns(20);
        CarObjTex.setRows(5);
        CarObjTex.setEnabled(false);
        jScrollPane1.setViewportView(CarObjTex);

        CarObjTex1.setColumns(20);
        CarObjTex1.setRows(5);
        CarObjTex1.setEnabled(false);
        jScrollPane4.setViewportView(CarObjTex1);

        TitLab.setText("Title");

        SexLab.setText("Sex");

        FirNamLab.setText("First Name");

        DurLab.setText("Duration");

        FirNameTex.setEnabled(false);
        FirNameTex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirNameTexActionPerformed(evt);
            }
        });

        LasNamLab.setText("Last Name");

        LasNamTex.setEnabled(false);
        LasNamTex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LasNamTexActionPerformed(evt);
            }
        });

        NUIDLab.setText("NU ID");

        NUIDTex.setEnabled(false);
        NUIDTex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUIDTexActionPerformed(evt);
            }
        });

        StrLin1Tex.setEnabled(false);
        StrLin1Tex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StrLin1TexActionPerformed(evt);
            }
        });

        AddLab.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        AddLab.setText("Address");

        StrLin2Tex.setEnabled(false);
        StrLin2Tex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StrLin2TexActionPerformed(evt);
            }
        });

        Str1Lab.setText("Street Line 1");

        CityTex.setEnabled(false);
        CityTex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityTexActionPerformed(evt);
            }
        });

        Str2Lab.setText("Street Line 2");

        CityLab.setText("City");

        CerLab.setText("Certifications");

        CouTex.setEnabled(false);
        CouTex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CouTexActionPerformed(evt);
            }
        });

        SkiLab.setText("Skills");

        AffTex.setEnabled(false);
        AffTex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AffTexActionPerformed(evt);
            }
        });

        CountryLab.setText("Country");

        EDegTex.setEnabled(false);
        EDegTex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDegTexActionPerformed(evt);
            }
        });

        CerTex.setEnabled(false);
        CerTex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerTexActionPerformed(evt);
            }
        });

        AffLab.setText("Affiliation");

        EMajTex.setEnabled(false);
        EMajTex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EMajTexActionPerformed(evt);
            }
        });

        SkiTex.setEnabled(false);
        SkiTex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SkiTexActionPerformed(evt);
            }
        });

        CarObjLab.setText("Carrier Objective Statement");

        EDatTex.setEnabled(false);
        EDatTex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDatTexActionPerformed(evt);
            }
        });

        EduLab.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EduLab.setText("Education");

        WTitTex.setEnabled(false);
        WTitTex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WTitTexActionPerformed(evt);
            }
        });

        DegLab.setText("Degree");

        WCNamTex.setEnabled(false);
        WCNamTex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WCNamTexActionPerformed(evt);
            }
        });

        MajLab.setText("Major");

        WDurTex.setEnabled(false);
        WDurTex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WDurTexActionPerformed(evt);
            }
        });

        DateLab.setText("Dated");

        WorExpLab.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        WorExpLab.setText("Work Experience");

        HeadlingLab.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        HeadlingLab.setText("Resume Submitted");

        SexTex.setEnabled(false);

        PicLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/default.png-128x128x2.png"))); // NOI18N
        PicLab.setLabelFor(PicLab);
        PicLab.setBorder(new javax.swing.border.MatteBorder(null));

        ExiBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/exit-button.png"))); // NOI18N
        ExiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExiBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("EXIT here  ---->");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/Job Fair.png"))); // NOI18N

        VitalJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NUID", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(VitalJTable);

        VitalJTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NUID", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(VitalJTable1);

        VieBtn.setText("View");
        VieBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VieBtnActionPerformed(evt);
            }
        });

        DelBtn.setText("Delete");
        DelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelBtnActionPerformed(evt);
            }
        });

        LabCitizen.setText("Citizenship");

        TexCitizen.setEnabled(false);
        TexCitizen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TexCitizenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ScrJPanelLayout = new javax.swing.GroupLayout(ScrJPanel);
        ScrJPanel.setLayout(ScrJPanelLayout);
        ScrJPanelLayout.setHorizontalGroup(
            ScrJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScrJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ScrJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ScrJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ScrJPanelLayout.createSequentialGroup()
                            .addGroup(ScrJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LasNamLab)
                                .addComponent(NUIDLab)
                                .addComponent(SexLab))
                            .addGap(18, 18, 18)
                            .addGroup(ScrJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NUIDTex, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SexTex, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(238, 238, 238))
                        .addGroup(ScrJPanelLayout.createSequentialGroup()
                            .addGroup(ScrJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(LasNamTex, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(ScrJPanelLayout.createSequentialGroup()
                                    .addComponent(FirNamLab)
                                    .addGap(18, 18, 18)
                                    .addComponent(FirNameTex, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(186, 186, 186)))
                    .addGroup(ScrJPanelLayout.createSequentialGroup()
                        .addGroup(ScrJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ScrJPanelLayout.createSequentialGroup()
                                .addComponent(WorExpLab)
                                .addGap(18, 18, 18)
                                .addGroup(ScrJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ComNamLab)
                                    .addComponent(DurLab, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(ScrJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(WDurTex, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(WCNamTex, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(86, 86, 86)
                                .addComponent(TitLab)
                                .addGap(26, 26, 26)
                                .addComponent(WTitTex, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(AffLab)
                            .addGroup(ScrJPanelLayout.createSequentialGroup()
                                .addGroup(ScrJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ScrJPanelLayout.createSequentialGroup()
                                        .addGroup(ScrJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CerLab)
                                            .addComponent(SkiLab))
                                        .addGap(18, 18, 18)
                                        .addGroup(ScrJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(SkiTex)
                                            .addComponent(CerTex, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ScrJPanelLayout.createSequentialGroup()
                                        .addComponent(EduLab)
                                        .addGap(18, 18, 18)
                                        .addComponent(DegLab)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EDegTex, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(52, 52, 52)
                                        .addComponent(MajLab)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EMajTex, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(DateLab)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(EDatTex, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ScrJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ScrJPanelLayout.createSequentialGroup()
                                    .addComponent(CarObjLab)
                                    .addGap(26, 26, 26)
                                    .addComponent(jScrollPane1))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ScrJPanelLayout.createSequentialGroup()
                                    .addComponent(AddLab)
                                    .addGap(28, 28, 28)
                                    .addGroup(ScrJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(AffTex, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(ScrJPanelLayout.createSequentialGroup()
                                            .addGroup(ScrJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(ScrJPanelLayout.createSequentialGroup()
                                                    .addComponent(CityLab)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(CityTex, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(ScrJPanelLayout.createSequentialGroup()
                                                    .addComponent(Str1Lab)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(StrLin1Tex, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(47, 47, 47)
                                            .addGroup(ScrJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(ScrJPanelLayout.createSequentialGroup()
                                                    .addComponent(Str2Lab)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(StrLin2Tex, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(ScrJPanelLayout.createSequentialGroup()
                                                    .addGroup(ScrJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(LabCitizen)
                                                        .addComponent(CountryLab))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(ScrJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(CouTex, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                                        .addComponent(TexCitizen)))))
                                        .addGroup(ScrJPanelLayout.createSequentialGroup()
                                            .addGap(226, 226, 226)
                                            .addComponent(VieBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(DelBtn)))))
                            .addGroup(ScrJPanelLayout.createSequentialGroup()
                                .addGap(416, 416, 416)
                                .addComponent(PicLab, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ScrJPanelLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(ScrJPanelLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(HeadlingLab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ExiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addContainerGap())
        );
        ScrJPanelLayout.setVerticalGroup(
            ScrJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScrJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ScrJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ScrJPanelLayout.createSequentialGroup()
                        .addGroup(ScrJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HeadlingLab)
                            .addGroup(ScrJPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(ExiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ScrJPanelLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ScrJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VieBtn)
                            .addComponent(DelBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(ScrJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ScrJPanelLayout.createSequentialGroup()
                                .addGroup(ScrJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(FirNamLab)
                                    .addComponent(FirNameTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addGroup(ScrJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LasNamLab)
                                    .addComponent(LasNamTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ScrJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(NUIDLab)
                                    .addComponent(NUIDTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(ScrJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SexLab)
                                    .addComponent(SexTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(PicLab, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(ScrJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddLab)
                            .addComponent(Str1Lab)
                            .addComponent(Str2Lab)
                            .addComponent(StrLin1Tex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StrLin2Tex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ScrJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CityLab)
                            .addComponent(CountryLab)
                            .addComponent(CityTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CouTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ScrJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AffLab)
                            .addComponent(AffTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabCitizen)
                            .addComponent(TexCitizen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ScrJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CarObjLab)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ScrJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EDegTex, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ScrJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(EduLab)
                                .addComponent(DegLab)
                                .addComponent(MajLab)
                                .addComponent(DateLab)
                                .addComponent(EDatTex, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(EMajTex, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(ScrJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CerLab)
                            .addComponent(CerTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ScrJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SkiLab)
                            .addComponent(SkiTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ScrJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WorExpLab)
                            .addComponent(ComNamLab)
                            .addComponent(TitLab)
                            .addComponent(WTitTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WCNamTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ScrJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WDurTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DurLab))
                        .addGap(80, 80, 80))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jScrollPane2.setViewportView(ScrJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 871, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AffTexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AffTexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AffTexActionPerformed

    private void CouTexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CouTexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CouTexActionPerformed

    private void WDurTexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WDurTexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WDurTexActionPerformed

    private void CityTexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityTexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CityTexActionPerformed

    private void WCNamTexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WCNamTexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WCNamTexActionPerformed

    private void WTitTexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WTitTexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WTitTexActionPerformed

    private void StrLin2TexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StrLin2TexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StrLin2TexActionPerformed

    private void StrLin1TexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StrLin1TexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StrLin1TexActionPerformed

    private void EDatTexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDatTexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EDatTexActionPerformed

    private void NUIDTexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUIDTexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NUIDTexActionPerformed

    private void SkiTexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SkiTexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SkiTexActionPerformed

    private void LasNamTexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LasNamTexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LasNamTexActionPerformed

    private void EMajTexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EMajTexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EMajTexActionPerformed

    private void FirNameTexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirNameTexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirNameTexActionPerformed

    private void CerTexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerTexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CerTexActionPerformed

    private void EDegTexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDegTexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EDegTexActionPerformed

    private void ExiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExiBtnActionPerformed
        System.exit(0);
        
// TODO add your handling code here:
    }//GEN-LAST:event_ExiBtnActionPerformed

    private void VieBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VieBtnActionPerformed
        int selectedrow = VitalJTable.getSelectedRow();
        
        if(selectedrow >=0)
        {
            Resume rm = (Resume)VitalJTable.getValueAt(selectedrow, 0);
            FirNameTex.setText(String.valueOf(rm.getFirstName()));
            LasNamTex.setText(String.valueOf(rm.getLastName()));
            NUIDTex.setText(String.valueOf(rm.getNUID()));
            SexTex.setText(String.valueOf(rm.getSex()));
            TexCitizen.setText(String.valueOf(rm.getCitizenship()));
            
            StrLin1Tex.setText(String.valueOf(rm.getStreetLine1()));
            StrLin2Tex.setText(String.valueOf(rm.getStreetLine2()));
            CityTex.setText(String.valueOf(rm.getCity()));
            CouTex.setText(String.valueOf(rm.getCountry()));
            AffTex.setText(String.valueOf(rm.getAffiliation()));
            CarObjTex.setText(String.valueOf(rm.getObjective()));
            EDegTex.setText(String.valueOf(rm.getEDegree()));
            EMajTex.setText(String.valueOf(rm.getEMajor()));
            EDatTex.setText(String.valueOf(rm.getEdate()));
            CerTex.setText(String.valueOf(rm.getCertifications()));
 //           SkiTex.setText(String.valueOf(rm.getSkills()));
 
            SkiTex.setText(String.valueOf(rm.getSkills() + "  " + rm.getSkill1() + "  " + rm.getSkill2() + "  " + rm.getSkill3()));
            WCNamTex.setText(String.valueOf(rm.getWCompanyName()));
            WTitTex.setText(String.valueOf(rm.getWTitle()));
            WDurTex.setText(String.valueOf(rm.getWDuration()));
            
            ImageIcon ProfilePic=new ImageIcon(rm.getPicture());
        PicLab.setIcon(ProfilePic);
            
        
        }
        else
            JOptionPane.showMessageDialog(null, "Please Select any row");
       
    }//GEN-LAST:event_VieBtnActionPerformed

    private void DelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelBtnActionPerformed
        
        int p = JOptionPane.showConfirmDialog(null, "Do you really want to Delete?","Delete",JOptionPane.YES_NO_OPTION);
        if (p==0)
        {
        
        int selectedrow = VitalJTable.getSelectedRow();
        
        if(selectedrow >=0)
        {
            Resume rm = (Resume)VitalJTable.getValueAt(selectedrow, 0);
            rmh.deleteResume(rm);
     //       JOptionPane.YES_NO_OPTION()
            JOptionPane.showMessageDialog(null, "Resume has been deleted");
            populateTable();
            
            
            
        }
        else
            JOptionPane.showMessageDialog(null, "Please Select any row");

        }
// TODO add your handling code here:
    }//GEN-LAST:event_DelBtnActionPerformed

    private void TexCitizenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TexCitizenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TexCitizenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddLab;
    private javax.swing.JLabel AffLab;
    private javax.swing.JTextField AffTex;
    private javax.swing.JLabel CarObjLab;
    private javax.swing.JTextArea CarObjTex;
    private javax.swing.JTextArea CarObjTex1;
    private javax.swing.JLabel CerLab;
    private javax.swing.JTextField CerTex;
    private javax.swing.JLabel CityLab;
    private javax.swing.JTextField CityTex;
    private javax.swing.JLabel ComNamLab;
    private javax.swing.JTextField CouTex;
    private javax.swing.JLabel CountryLab;
    private javax.swing.JLabel DateLab;
    private javax.swing.JLabel DegLab;
    private javax.swing.JButton DelBtn;
    private javax.swing.JLabel DurLab;
    private javax.swing.JTextField EDatTex;
    private javax.swing.JTextField EDegTex;
    private javax.swing.JTextField EMajTex;
    private javax.swing.JLabel EduLab;
    private javax.swing.JButton ExiBtn;
    private javax.swing.JLabel FirNamLab;
    private javax.swing.JTextField FirNameTex;
    private javax.swing.JLabel HeadlingLab;
    private javax.swing.JLabel LabCitizen;
    private javax.swing.JLabel LasNamLab;
    private javax.swing.JTextField LasNamTex;
    private javax.swing.JLabel MajLab;
    private javax.swing.JLabel NUIDLab;
    private javax.swing.JTextField NUIDTex;
    private javax.swing.JLabel PicLab;
    private javax.swing.JPanel ScrJPanel;
    private javax.swing.JLabel SexLab;
    private javax.swing.JTextField SexTex;
    private javax.swing.JLabel SkiLab;
    private javax.swing.JTextField SkiTex;
    private javax.swing.JLabel Str1Lab;
    private javax.swing.JLabel Str2Lab;
    private javax.swing.JTextField StrLin1Tex;
    private javax.swing.JTextField StrLin2Tex;
    private javax.swing.JTextField TexCitizen;
    private javax.swing.JLabel TitLab;
    private javax.swing.JButton VieBtn;
    private javax.swing.JTable VitalJTable;
    private javax.swing.JTable VitalJTable1;
    private javax.swing.JTextField WCNamTex;
    private javax.swing.JTextField WDurTex;
    private javax.swing.JTextField WTitTex;
    private javax.swing.JLabel WorExpLab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables

   
}
