/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.SupplierRole;

import Business.Supplier;
import Business.SupplierDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Malick
 */
public class SupplierWorkAreaJPanel extends javax.swing.JPanel {
        
     JPanel userProcessControl;
    SupplierDirectory supplierDirectory;
    Supplier supplier;
    
    /**
     * Creates new form SupplierWorkAreaJPanel
     */
    public SupplierWorkAreaJPanel(JPanel userProcessControl, Supplier supplier) {
        initComponents();
         this.userProcessControl = userProcessControl;
        this.supplier = supplier;
        
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManageProdCat = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("My Work Area - (Project Manager Role)");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        btnManageProdCat.setText("Manage Product Catalog >>");
        btnManageProdCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageProdCatActionPerformed(evt);
            }
        });
        add(btnManageProdCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageProdCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageProdCatActionPerformed
         ManageProductCatalogJPanel mpcjp =  new ManageProductCatalogJPanel(userProcessControl, supplier);
        userProcessControl.add("ManageProductCatalogJPanel", mpcjp);
        CardLayout layout = (CardLayout)userProcessControl.getLayout();
        layout.next(userProcessControl);
    }//GEN-LAST:event_btnManageProdCatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageProdCat;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
