/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.SupplierRole;

import Business.Product;
import Business.Supplier;
import Business.SupplierDirectory;
import javax.swing.JPanel;
import Business.ProductCatalog;
import java.awt.CardLayout;

/**
 *
 * @author Malick
 */
public class ViewProductDetailJPanel extends javax.swing.JPanel {

      JPanel userProcessControl;
    SupplierDirectory supplierDirectory;
    Supplier supplier;
    Product p;
    /**
     * Creates new form ViewProductDetailJPanel
     */
    public ViewProductDetailJPanel(JPanel userProcessControl, Product p) {
        initComponents();
           this.userProcessControl = userProcessControl;
        this.p = p;
        txtProductName.setText(p.getProductName());
        txtProductID.setText(String.valueOf(p.getModelNumber()));
        txtProductPrice.setText(String.valueOf(p.getPrice()));
        
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtProductName = new javax.swing.JTextField();
        txtProductID = new javax.swing.JTextField();
        txtProductPrice = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdateProduct = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("View Product Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 24, -1, -1));

        jLabel2.setText("Product Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 80, -1, -1));

        jLabel3.setText("Product ID");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 121, -1, -1));

        jLabel4.setText("Product Price");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 174, -1, -1));

        txtProductName.setText(" ");
        txtProductName.setEnabled(false);
        add(txtProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 77, 120, -1));

        txtProductID.setText(" ");
        txtProductID.setEnabled(false);
        add(txtProductID, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 118, 120, -1));

        txtProductPrice.setText(" ");
        txtProductPrice.setEnabled(false);
        add(txtProductPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 171, 120, -1));

        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 226, -1, -1));

        btnSave.setText("save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 226, -1, -1));

        btnUpdateProduct.setText("Update Product");
        btnUpdateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateProductActionPerformed(evt);
            }
        });
        add(btnUpdateProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 226, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateProductActionPerformed
        txtProductName.setEnabled(true);
    //    txtProductID.setEditable(true);
        txtProductPrice.setEnabled(true);
        btnSave.setEnabled(true);
        btnUpdateProduct.setEnabled(false);
        
        
    }//GEN-LAST:event_btnUpdateProductActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        p.setPrice(Integer.parseInt(txtProductPrice.getText()));
        p.setProductName(txtProductName.getText());
        btnSave.setEnabled(false);
        btnUpdateProduct.setEnabled(true);
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessControl.remove(this);
        CardLayout layout = (CardLayout) userProcessControl.getLayout();
        layout.previous(userProcessControl);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdateProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtProductID;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtProductPrice;
    // End of variables declaration//GEN-END:variables
}
