/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.AccountDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Malick
 */
public class AcctMangrJPanel extends javax.swing.JPanel {

    
    private JPanel userProcessContainer;
    private AccountDirectory accountDirectory;
    
    
    /**
     * Creates new form AcctMangrJPanel
     */
  
    AcctMangrJPanel(JPanel userProcessContainer, AccountDirectory accountDirectory) {
            initComponents();
            this.userProcessContainer = userProcessContainer;
            this.accountDirectory = accountDirectory;
            
             
            
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnCreateAcct = new javax.swing.JButton();
        BrnManageAcct = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(900, 600));

        BtnCreateAcct.setText("Create");
        BtnCreateAcct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCreateAcctActionPerformed(evt);
            }
        });

        BrnManageAcct.setText("Manage Account");
        BrnManageAcct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrnManageAcctActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BrnManageAcct, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(BtnCreateAcct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(401, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(BtnCreateAcct, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(BrnManageAcct, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(330, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCreateAcctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCreateAcctActionPerformed
           CreateAcctJPanel panel = new CreateAcctJPanel(userProcessContainer, accountDirectory);
           userProcessContainer.add("CreateAcctJPanel", panel);
           CardLayout layout = (CardLayout) userProcessContainer.getLayout();
           layout.next(userProcessContainer);  



// TODO add your handling code here:
    }//GEN-LAST:event_BtnCreateAcctActionPerformed

    private void BrnManageAcctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrnManageAcctActionPerformed
        ManageAccountJPanel panel = new ManageAccountJPanel(userProcessContainer, accountDirectory);
        userProcessContainer.add("ManageAccountJPanel", panel);
           CardLayout layout = (CardLayout) userProcessContainer.getLayout();
           layout.next(userProcessContainer); 


// TODO add your handling code here:
    }//GEN-LAST:event_BrnManageAcctActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BrnManageAcct;
    private javax.swing.JButton BtnCreateAcct;
    // End of variables declaration//GEN-END:variables
}
