/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Account;
import Business.AccountDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Malick
 */
public class CreateAcctJPanel extends javax.swing.JPanel {

    
    private JPanel userProcessContainer;
     private AccountDirectory accountDirectory;
       
    /**
     * Creates new form CreateAcctJPanel
     */
    CreateAcctJPanel(JPanel userProcessContainer, AccountDirectory accountDirectory) {
       initComponents();
       
       this.userProcessContainer = userProcessContainer;
            this.accountDirectory = accountDirectory;
            
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtRoutNum = new javax.swing.JTextField();
        txtAcctNum = new javax.swing.JTextField();
        txtBankNam = new javax.swing.JTextField();
        txtBalance = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Account");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, 880, 27));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Routing Number");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 93, 129, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Account Numer");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 134, 129, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Bank Name");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 172, 129, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Balance");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 210, 129, -1));

        txtRoutNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoutNumActionPerformed(evt);
            }
        });
        add(txtRoutNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 195, -1));
        add(txtAcctNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 131, 195, -1));
        add(txtBankNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 169, 195, -1));
        add(txtBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 207, 195, -1));

        btnCreate.setText("Create Account");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 195, 36));

        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 89, 92, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtRoutNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoutNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoutNumActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
            String rountingNumber = txtRoutNum.getText();
            String accountNumber = txtAcctNum.getText();
            String bankName = txtBankNam.getText();
            int balance = Integer.parseInt(txtBalance.getText());
            
            
            Account account = accountDirectory.addAccount();
            account.setRountingNumber(rountingNumber);
            account.setAccountNumber(accountNumber);
            account.setBankName(bankName);
            account.setBalance(balance);
            
            JOptionPane.showMessageDialog(null, "Account Successfully Created");
            
            
            

// TODO add your handling code here:
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
            userProcessContainer.remove(this);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.previous(userProcessContainer);
            




// TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtAcctNum;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtBankNam;
    private javax.swing.JTextField txtRoutNum;
    // End of variables declaration//GEN-END:variables
}
