/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Account;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Malick
 */
public class ViewAccountJPanel extends javax.swing.JPanel {

    
    private JPanel userProcessContainer;
    private Account account;
    
    /**
     * Creates new form ViewAccountJPanel
     */
  
    ViewAccountJPanel(JPanel userProcessContainer, Account account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        populateAccountDetails();
        btnsave.setEnabled(false);
        btnUpdate.setEnabled(true);
        txtRoutNum.setEditable(false);
        txtAcctNum.setEditable(false);
        txtBankNam.setEditable(false);
   
    }
    
     private void populateAccountDetails() {
     txtRoutNum.setText(account.getRountingNumber());
     txtAcctNum.setText(account.getAccountNumber());
     txtBankNam.setText(account.getBankName());
     
          
     
     
     }
     
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtRoutNum = new javax.swing.JTextField();
        txtAcctNum = new javax.swing.JTextField();
        txtBankNam = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Account");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, 880, 27));

        txtRoutNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoutNumActionPerformed(evt);
            }
        });
        add(txtRoutNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 195, -1));
        add(txtAcctNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 131, 195, -1));
        add(txtBankNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 169, 195, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Bank Name");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 172, 129, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Account Numer");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 134, 129, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Routing Number");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 93, 129, -1));

        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 89, 92, -1));

        btnsave.setText("Save");
        btnsave.setEnabled(false);
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 246, -1, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 246, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtRoutNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoutNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoutNumActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        account.setRountingNumber(txtRoutNum.getText());
        account.setAccountNumber(txtAcctNum.getText());
        account.setBankName(txtBankNam.getText());
                txtRoutNum.setEditable(false);
        txtAcctNum.setEditable(false);
        txtBankNam.setEditable(false);
        btnsave.setEnabled(false);
        btnUpdate.setEnabled(true);
        
        JOptionPane.showMessageDialog(null, "Account updated successfully");


// TODO add your handling code here:
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        txtRoutNum.setEditable(true);
        txtAcctNum.setEditable(true);
        txtBankNam.setEditable(true);
        btnsave.setEnabled(true);
        btnUpdate.setEnabled(false);
        


// TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnsave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtAcctNum;
    private javax.swing.JTextField txtBankNam;
    private javax.swing.JTextField txtRoutNum;
    // End of variables declaration//GEN-END:variables

   
}
