/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.VitalSignHistory;
import Business.VitalSigns;
import javax.swing.JOptionPane;

/**
 *
 * @author Malick
 */
public class CreateVitalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateVitalJPanel
     */
 
    private VitalSignHistory vsh;
    public CreateVitalJPanel(VitalSignHistory vsh) {
        initComponents();
        this.vsh = vsh;

        
//To change body of generated methods, choose Tools | Templates.
    }

    // CreateVitalJPanel(VitalSignHistory vsh) {
    //    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    // }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabTemp = new javax.swing.JLabel();
        TxtTemp = new javax.swing.JTextField();
        LabTemp1 = new javax.swing.JLabel();
        TxtBloodPressure = new javax.swing.JTextField();
        LabTemp2 = new javax.swing.JLabel();
        TxtPulse = new javax.swing.JTextField();
        LabTemp3 = new javax.swing.JLabel();
        TxtDate = new javax.swing.JTextField();
        CreateHead = new javax.swing.JLabel();
        BtnSave = new javax.swing.JButton();

        LabTemp.setText("Temperature");

        TxtTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTempActionPerformed(evt);
            }
        });

        LabTemp1.setText("Blood Pressure");

        TxtBloodPressure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBloodPressureActionPerformed(evt);
            }
        });

        LabTemp2.setText("Pulse");

        TxtPulse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPulseActionPerformed(evt);
            }
        });

        LabTemp3.setText("Date");

        TxtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDateActionPerformed(evt);
            }
        });

        CreateHead.setBackground(new java.awt.Color(255, 255, 255));
        CreateHead.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CreateHead.setText("Create Vital Signs");

        BtnSave.setText("SAVE");
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(CreateHead))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabTemp3)
                                .addGap(61, 61, 61)
                                .addComponent(TxtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabTemp2)
                                .addGap(61, 61, 61)
                                .addComponent(TxtPulse, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabTemp1)
                                .addGap(61, 61, 61)
                                .addComponent(TxtBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabTemp)
                                .addGap(61, 61, 61)
                                .addComponent(TxtTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BtnSave))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(CreateHead)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabTemp)
                    .addComponent(TxtTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabTemp1)
                    .addComponent(TxtBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabTemp2)
                    .addComponent(TxtPulse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabTemp3)
                    .addComponent(TxtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BtnSave)
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TxtTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTempActionPerformed

    private void TxtBloodPressureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBloodPressureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBloodPressureActionPerformed

    private void TxtPulseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPulseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPulseActionPerformed

    private void TxtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDateActionPerformed

    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        double temperature = Double.parseDouble(TxtTemp.getText());
        double bp = Double.parseDouble(TxtBloodPressure.getText());
        int pulse = Integer.parseInt(TxtPulse.getText());
        String date = TxtDate.getText();
        VitalSigns v = vsh.addVitals();
        v.setBloodPressure((float) bp);
        v.setTemperature(temperature);
        v.setPulse(pulse);
        v.setDate(date);
        JOptionPane.showMessageDialog(null, "VitalSigns Added Sucessfully");
        
        TxtTemp.setText("");
        TxtBloodPressure.setText("");
        TxtPulse.setText("");
        TxtDate.setText("");
        
        

// TODO add your handling code here:
    }//GEN-LAST:event_BtnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSave;
    private javax.swing.JLabel CreateHead;
    private javax.swing.JLabel LabTemp;
    private javax.swing.JLabel LabTemp1;
    private javax.swing.JLabel LabTemp2;
    private javax.swing.JLabel LabTemp3;
    private javax.swing.JTextField TxtBloodPressure;
    private javax.swing.JTextField TxtDate;
    private javax.swing.JTextField TxtPulse;
    private javax.swing.JTextField TxtTemp;
    // End of variables declaration//GEN-END:variables
}
